### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Samstiles** [n9i5a/hackathon-feb-2015#1]
The goal of this tool is to demonstrate whether or not, in the longrun, you will be financially better off having a degree depending on your chosen industry (VS working the minimum wage for those 4 years + not incurring any debt). Also, display alternative options once they have their end result.

what are our inputs?
- What is your name?
- What area(s) of study would you like to pursue?
- What province are you from?
- What is your gender?

what is our output? (comparisons if they chose multiple, and compare against no degree regardless)
- # of years to 'break even'
- alternatives career choices
- employment rate
- salary after X years

To Do List
- [x] convert csv's/pdfs to models in sails
- [x] input all data into the mysql tables
- [x] think of domain name (free .me domain)
- [x] purchase domain
- [x] get project set up (angular, bower, ui-router, ng-material)
- [x] figure out the application flow and determine what views are necessary
- [x] make table of similar careers
- [x] graphs and layout for front end
- [x] calcs
- [x] allow results to be public switch
- [x] email me my results checkbox
